driver:
  name: dokken
  require_chef_omnibus: latest
  privileged: true # because Docker and SystemD/Upstart

verifier:
  root_path: '/opt/verifier'
  sudo: false

transport:
  name: dokken

provisioner:
  name: dokken
  attributes:
    ibm-im-test:
      passport_advantage:
        user: <%= ENV['PASSPORTADV_USER'] %>
        password: <%= ENV['PASSPORTADV_PW'] %>

platforms:
  - name: centos-6
    driver:
      image: dokken/centos-6
      pid_one_command: /sbin/init
  - name: centos-7
    driver:
      image: dokken/centos-7
      intermediate_instructions:
        - RUN systemctl unmask network.service
        - RUN /usr/bin/echo 'NETWORKING=yes' > /etc/sysconfig/network
      pid_one_command: /usr/lib/systemd/systemd
      privileged: true
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro # required by systemd
  - name: ubuntu-20.04
    driver:
      image: dokken/ubuntu-20.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update    
  - name: ubuntu-22.10
    driver:
      image: dokken/ubuntu-22.10
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update

suites:
  - name: install_im
    run_list:
    - recipe[ibm-im-test::install_im]
  - name: install_passport
    run_list:
    - recipe[ibm-im-test::install_passport]
